### ISSUE TITLE
vmware_workstation provider suport

### ISSUE THREAD

**Issue by TyMac** [thecodeteam/vagrant#12]
Can vmware_workstation provider support be added? Seems like a natural support option ;)

**Comment by kacole2** [comment]
@TyMac today's market has shown the vast majority of people using VirtualBox far outweighs VMware Workstation or Fusion. We are putting our priorities into achieving maximum investment of our time. However, if you or anyone would like to contribute VMware based provider support for the Vagrant environments we happily accept PRs into our projects.

**Comment by kacole2** [comment]
closing this issue based on date and no further options in the pipeline to support Fusion or Workstation. However, if you would like to submit a PR and take care of maintenance for that particular platform, we are willing to take a closer look
