### ISSUE TITLE
playa-mesos method to override version is broken

### ISSUE THREAD

**Issue by cantbewong** [thecodeteam/vagrant#2]
The facility to elect an alternate non-default version of Mesos and the isolator results in installing the correct version of the Mesos binary but leaves the isolator an part of the configuration set for the default version.

These minor edits to the Vagrantfile fix the issue
-      if pmconf.mesos_release != "" && pmconf.has_key?("mesos_release")
- ```
   if pmconf.instance_variable_get(:@settings).include?('mess_release')
  ```
- ```
   if pmconf.isolator_version != "" && pmconf.has_key?("isolator_version") 
  ```
-      if pmconf.instance_variable_get(:@settings).include?('isolator_version')

**Comment by jonasrosland** [comment]
Since you committed your change, is this done? Can we close it?

**Comment by kacole2** [comment]
Old and playa-mesos is dead
