### ISSUE TITLE
Missing version

### ISSUE THREAD

**Issue by ggeldenhuis** [thecodeteam/vagrant#27]
The forge version of the module is 0.1.6. It is kinda expected that a matching version would be found in git. So the fix really at present would be to release a new forge version and remove older forge versions since there is not matching branch in git anymore.

**Comment by kacole2** [comment]
@ggeldenhuis can you bit a bit more descriptive of which vagrant instance you are referring to? Sorry there's a few in here and it gets confusing. We did opt to bundle them all together in one repo for consolidation sake.

**Comment by kacole2** [comment]
closing since there has been no response
