### ISSUE TITLE
rexray does not get installed in mdm1 

### ISSUE THREAD

**Issue by lukeshaughnessy** [thecodeteam/vagrant#62]
Per the Youtube demo:

[root@mdm1 ~]# rexray get-instance
-bash: rexray: command not found

[root@mdm1 bin]# find / -name rexray
[root@mdm1 bin]#

**Comment by kacole2** [comment]
Hey Luke, the video you are watching is probably very outdated. That command is no longer necessary. 

Follow the installation instructions located at rexray.codedellemc.com
