### ISSUE TITLE
Support for v3.0?

### ISSUE THREAD

**Issue by yadvr** [thecodeteam/vagrant#83]
Hi team, cc @kacole2 @cduchesne @codenrhoden

We're trying to explore a storage plugin feature with Apache CloudStack specifically for VxFlex/ScaleIO version 3.x. Are there any plans to support v3.x? From a client point of view, can we use v2.x vagrant boxes for development for developing integration against v3.x, i.e. are the v2.x APIs compatible with v3.x? Thanks.

**Comment by cduchesne** [comment]
For the most part, the APIs in v2 are very similar to v3. The one API change I have noticed when switching to v3 was with the ignoreScsiInitiators being removed from volume unmap parameters. This is a really minor change. Otherwise you can easily do your dev against v2.

**Comment by yadvr** [comment]
Thanks for confirming API compatibility @cduchesne I'll close the issue on your remark.
